version: '3'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./var/postgresql-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: info_tbot
      POSTGRES_USER: info_tbot
      POSTGRES_PASSWORD: info_tbot

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
