# Generated by Django 3.0.5 on 2020-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticCommandHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_type', models.PositiveSmallIntegerField(choices=[(0, 'Команда'), (1, 'Текст')], verbose_name='Тип обработчика')),
                ('handler_name', models.CharField(help_text='Сообщение на которое должен реагировать обработчик', max_length=255, verbose_name='Параметр обработчика')),
                ('text', models.TextField(help_text='Текст который отправит бот в ответ на вызов `параметра обработчика`', verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Статический текстовый обработчик',
                'verbose_name_plural': 'Статические текстовые обработчики',
            },
        ),
    ]
