# Generated by Django 3.0.6 on 2020-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_handlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartBotHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(default='start', help_text='Сообщение на которое должен реагировать обработчик', max_length=255, verbose_name='Параметр обработчика')),
                ('text', models.TextField(default='Hello', help_text='Текст который отправит бот в ответ на вызов `параметра обработчика`', verbose_name='Текст ответа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='StaticCommandHandler',
            new_name='StaticContentHandler',
        ),
    ]
