# Generated by Django 3.0.6 on 2020-05-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0001_initial'),
        ('static_handlers', '0002_auto_20200507_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startbothandler',
            options={'verbose_name': 'Стартовый обработчик'},
        ),
        migrations.AddField(
            model_name='startbothandler',
            name='keyboard',
            field=models.ManyToManyField(help_text='Клавиатура возвращаемая при команде /start', to='buttons.Button', verbose_name='Клавиатура'),
        ),
    ]
