# Generated by Django 3.0.6 on 2020-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Кнопки для взаимодействия с ботом', max_length=255, unique=True, verbose_name='Тайтл клавиши')),
                ('description', models.TextField(verbose_name='Описание клавиши')),
            ],
            options={
                'verbose_name': 'Клавиша',
                'verbose_name_plural': 'Клавиши',
            },
        ),
    ]
